function onPreSave(request, response, modules) {
  // The code below is auto-generated by the validation addon.
  // Do not change.
  if (!request.body || !request.body.message) {
    response.body.debug = "Not a valid message";
    response.complete(400);
  }
  
  
  
  var context = modules.backendContext;
  var logger = modules.logger;
  var userCollection = modules.collectionAccess.collection('user');
  userCollection.findOne({"username":context.getAuthenticatedUsername()},function(err,u){
//    modules.logger.info("body: "+JSON.stringify(u));
    if (err) {
      response.body.debug = err;
      response.complete(400);
    } else {
      var userEvent = u.event;
      var messageEvent = request.body.event;
      var targetUser = request.body.targetUser;
      if (targetUser) {
        userCollection.findOne({"_id":modules.collectionAccess.objectID(targetUser)}, function(err, tu) {
          if (err) {
            response.body.debug = err;
            response.complete(400);
          } else {
            if (!tu) {
              response.body.debug = "No user _id:"+targetUser;
              response.complete(400);
            }
            if (tu.event != messageEvent && u.event != messageEvent) {
              response.body.debug = "Target user is not a this event.";
              response.complete(400);
            } else {
              response.continue();
            }
          }
        });
      } else {
          response.body.debug = "No target user specified.";
          response.complete(400);
      }
    }
  });
  /*
  var result = modules.validation.doValidation(
    {"event":{"pattern":["Kinvey"]}},
    request.body
  );
  if(result.length > 0) {// Validation failed.
    response.body.debug = result;
    response.complete(400);
  }
  else {// Validation passed.
    response.continue();
  }
  // End auto-generated code.
*/
}